### ISSUE TITLE
Twingate Operator resource issue failt to recreate or remove

### ISSUE THREAD

**Issue by CPD-BenjaminDam** [Twingate/kubernetes-operator#156]
unexpected behavior for TwingateResource

case:
user creates resource and access with yaml. 
Admin then deletes resource from web interface

Expected result:
Operator recreates the resource.

Actual result:
Operator does not recreate the resource.

Experienced Failure Point:
when user removes resource and access with yaml it hangs and log shows.
```
Events:
  Type    Reason   Age    From  Message
  ----    ------   ----   ----  -------
  Normal  Logging  3m18s  kopf  Got a delete request: {'address': 'my.default.cluster.local', 'alias': 'mine.local', 'id': '<redacted id>', 'isBrowserShortcutEnabled': False, 'isVisible': True, 'name': 'My K8S Resource'}. Status: {'twingate_resource_create': {'created_at': '2024-02-16T10:25:31.640085+00:00', 'success': True, 'ts': '2024-02-16T10:25:32.167995', 'twingate_id': '<redacted id>', 'updated_at': '2024-02-16T10:25:31.640112+00:00'}, 'twingate_resource_update': {'created_at': '2024-02-16T10:25:31.640085+00:00', 'success': True, 'ts': '2024-02-16T10:25:33.459166', 'twingate_id': '<redacted id>', 'updated_at': '2024-02-16T10:25:33.179859+00:00'}}
  Normal  Logging  3m18s  kopf  Deleting resource <redacted id>
  Error   Logging  3m18s  kopf  Handler 'twingate_resource_delete' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/opt/.venv/lib/python3.11/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once
    result = await invoke_handler(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler
    result = await invocation.invoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3....^^^^^^^^^^^^^
  File "/app/app/handlers/handlers_resource.py", line 49, in twingate_resource_delete
    client.resource_delete(resource_id)
  File "/app/app/api/client_resources.py", line 266, in resource_delete
    result = self.execute_mutation(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/api/client.py", line 119, in execute_mutation
    raise GraphQLMutationError(f"{name} mutation failed.", data.get("error"))
app.api.client.GraphQLMutationError: resourceDelete mutation failed. mutation failed.
  Error  Logging  2m17s  kopf  Handler 'twingate_resource_delete' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/opt/.venv/lib/python3.11/site-packages/kopf/_core/actions/execution.py", line 276, in execute_handler_once
    result = await invoke_handler(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3.11/site-packages/kopf/_core/actions/execution.py", line 371, in invoke_handler
    result = await invocation.invoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.venv/lib/python3....^^^^^^^^^^^^^
  File "/app/app/handlers/handlers_resource.py", line 49, in twingate_resource_delete
    client.resource_delete(resource_id)
  File "/app/app/api/client_resources.py", line 266, in resource_delete
    result = self.execute_mutation(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/api/client.py", line 119, in execute_mutation
    raise GraphQLMutationError(f"{name} mutation failed.", data.get("error"))
app.api.client.GraphQLMutationError: resourceDelete mutation failed. mutation failed.

```

Expected ways to resolve this hang:

```
kubectl delete twingateresources.twingate.com my-twingate-resource --grace-period 0 --force
no return or failure to delete resource
```

```
kubectl patch twingateresources.twingate.com my-twingate-resource -p '{"metadata": {"finalizers": null}}'
error: application/strategic-merge-patch+json is not supported by twingate.com/v1beta, Kind=TwingateResource: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml
```

myresource.yaml deployed
```
apiVersion: twingate.com/v1beta
kind: TwingateResource
metadata:
  name: my-twingate-resource
spec:
  name: My K8S Resource
  address: my.default.cluster.local
  alias: mine.local
---
apiVersion: twingate.com/v1beta
kind: TwingateResourceAccess
metadata:
  name: my-twingate-access
spec:
  resourceRef:
    name: my-twingate-resource
    namespace: default
  principalId: <redacted id>
```

Twignate Operator Deployment Method:
this command was run February 15th 2024 by first cloning the github repo. due to missing helm repo for this.
```
helm install --namespace=twingate-operator --set image.tag=0.3.0 --set twingateOperator.network=XXXXX --set twingateOperator.remoteNetworkName=<redacted network name> --set twingateOperator.apiKey=xxxxxxxxxxx twingate-operator ./twingate-operator
```

**Comment by ekampf** [comment]
@CPD-BenjaminDam confirming this is a case we dont handle at the moment - need to add a cron that keeps checking connector objects making sure they're still in the Twingate Admin and recreate if not.
Will prioritize ASAP

**Comment by ekampf** [comment]
@CPD-BenjaminDam deletion issue is handled by #160 - delting an entity already deleted should be a success.
Re the sync issue - if an admin deletes the resource in the web console there's no way for operator to find out immediately.
The only way at the moment is to continually poll the API and make sure data is in sync.
Right now this is done every 10h: 
https://github.com/Twingate/kubernetes-operator/blob/main/app/handlers/handlers_resource.py#L55

**Comment by ekampf** [comment]
@CPD-BenjaminDam `v0.5.0` is out :)
https://github.com/Twingate/kubernetes-operator/releases/tag/v0.5.0
